# Site settings
title: "Plotly Academy"
description: "Tutorials and workshops on the open-source stack used by <a href='https://twitter.com/plotlygraphs'>@plotlygraphs</a>"
url: "http://academy.plot.ly"
exclude: [node_modules, scripts, weather-app, react-app]

# Tutorials
collections:
  react:
    output: true
    permalink: /react/:path/
    title: "Build your first real world React.js application with <a href='https://twitter.com/mxstbr'>@mxstbr</a>"
    category: "Frontend"
  ipython-notebook:
    output: false
    title: "IPython Notebook Tutorial"
    category: "Data Science"

# Link style
permalink: /:year/:month/:title

# Default YAML Front Matter
defaults:
  scope:
    path: ""
    type: "posts"
  values:
    layout: "post"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [smart, no_intra_emphasis, tables, fenced_code_blocks, lax_spacing, footnotes, disable_indented_code_blocks, superscript, with_toc_data]
sass:
  sass_dir: _sass
  style: expanded
  deploy_style: compressed
